-- =====================================================================
-- Royal Square Financial — demo seed data (FICTIONAL people and policies)
-- GENERATED by scripts/generate-seed.mjs from src/data/mockData.js.
-- Do not hand-edit: change mockData.js and run `npm run seed:generate`.
--
-- Run AFTER supabase/schema.sql. Safe to re-run (on conflict do nothing).
-- Provider integrations are mock only.
--
-- To sign in as the demo users, create auth users (Authentication → Users →
-- Add user) with these emails; the auth trigger links them automatically:
--   Client : lerato.molefe@example.demo
--   Adviser: sipho.ndlovu@royalsquare.demo
-- =====================================================================

-- Timestamp helper: day offset + South African clock time, relative to today.
create or replace function public.rsf_seed_ts(day_offset int, hh int, mi int)
returns timestamptz
language sql stable
as $$
  select (date_trunc('day', now() at time zone 'Africa/Johannesburg')
          + make_interval(days => day_offset, hours => hh, mins => mi)) at time zone 'Africa/Johannesburg';
$$;

insert into public.advisers (id, full_name, email, phone, region, fsp_rep_number) values
  ('a0000000-0000-4000-8000-000000000001'::uuid, 'Sipho Ndlovu', 'sipho.ndlovu@royalsquare.demo', '021 555 0101', 'Cape Town', 'REP-DEMO-1042'),
  ('a0000000-0000-4000-8000-000000000002'::uuid, 'Michelle van der Merwe', 'michelle.vdm@royalsquare.demo', '021 555 0102', 'Stellenbosch', 'REP-DEMO-1077')
on conflict do nothing;

insert into public.providers (id, name, category, contact_email, avg_response_days, integration_mode) values
  ('b0000000-0000-4000-8000-000000000001'::uuid, 'Santam', 'Short-term insurance', 'claims@santam.demo', 2, 'mock'),
  ('b0000000-0000-4000-8000-000000000002'::uuid, 'Discovery', 'Life and health insurance', 'service@discovery.demo', 4, 'mock'),
  ('b0000000-0000-4000-8000-000000000003'::uuid, 'Sanlam', 'Life insurance and retirement', 'service@sanlam.demo', 3, 'mock'),
  ('b0000000-0000-4000-8000-000000000004'::uuid, 'Momentum', 'Investments and life insurance', 'service@momentum.demo', 3, 'mock'),
  ('b0000000-0000-4000-8000-000000000005'::uuid, 'Allan Gray', 'Investments', 'service@allangray.demo', 2, 'mock')
on conflict do nothing;

insert into public.clients (id, first_name, last_name, email, phone, id_number_masked, date_of_birth, address_line, city, postal_code, occupation, vehicle_description, total_assets, total_liabilities) values
  ('c0000000-0000-4000-8000-000000000001'::uuid, 'Lerato', 'Molefe', 'lerato.molefe@example.demo', '082 555 0141', '900312 **** ***', '1990-03-12'::date, '14 Protea Road, Rondebosch', 'Cape Town', '7700', 'Pharmacist', '2021 Toyota Corolla Cross · CA 123-456', 1530000, 290000),
  ('c0000000-0000-4000-8000-000000000002'::uuid, 'Thandi', 'Jacobs', 'thandi.jacobs@example.demo', '083 555 0199', '850721 **** ***', '1985-07-21'::date, '7 Harbour View, Gordon''s Bay', 'Cape Town', '7140', 'Civil engineer', null, 2380000, 910000),
  ('c0000000-0000-4000-8000-000000000003'::uuid, 'Johan', 'Pretorius', 'johan.p@example.demo', '072 555 0133', '680904 **** ***', '1968-09-04'::date, '22 Dennesig Street', 'Stellenbosch', '7600', 'Wine farm manager', null, 5120000, 640000),
  ('c0000000-0000-4000-8000-000000000004'::uuid, 'Ayesha', 'Patel', 'ayesha.patel@example.demo', '084 555 0177', '930115 **** ***', '1993-01-15'::date, '3 Kloof Nek Road, Tamboerskloof', 'Cape Town', '8001', 'Software developer', null, 780000, 215000),
  ('c0000000-0000-4000-8000-000000000005'::uuid, 'Bongani', 'Dlamini', 'bongani.d@example.demo', '076 555 0112', '890630 **** ***', '1989-06-30'::date, '14 Protea Road, Rondebosch', 'Cape Town', '7700', 'Teacher', null, 640000, 120000)
on conflict do nothing;

insert into public.client_adviser_assignments (client_id, adviser_id, is_primary) values
  ('c0000000-0000-4000-8000-000000000001'::uuid, 'a0000000-0000-4000-8000-000000000001'::uuid, true),
  ('c0000000-0000-4000-8000-000000000002'::uuid, 'a0000000-0000-4000-8000-000000000001'::uuid, true),
  ('c0000000-0000-4000-8000-000000000003'::uuid, 'a0000000-0000-4000-8000-000000000002'::uuid, true),
  ('c0000000-0000-4000-8000-000000000004'::uuid, 'a0000000-0000-4000-8000-000000000001'::uuid, true),
  ('c0000000-0000-4000-8000-000000000005'::uuid, 'a0000000-0000-4000-8000-000000000002'::uuid, true)
on conflict do nothing;

insert into public.households (id, name) values
  ('d0000000-0000-4000-8000-000000000001'::uuid, 'Molefe–Dlamini household')
on conflict do nothing;

insert into public.household_members (household_id, client_id) values
  ('d0000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid),
  ('d0000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000005'::uuid)
on conflict do nothing;

insert into public.client_products (id, client_id, provider_id, product_type, policy_number, description) values
  ('80000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000001'::uuid, 'Vehicle insurance', 'SAN-DEMO-44821', 'Comprehensive motor cover'),
  ('80000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000001'::uuid, 'Personal insurance', 'SAN-DEMO-44822', 'Home contents'),
  ('80000000-0000-4000-8000-000000000003'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000003'::uuid, 'Life cover', 'SLM-DEMO-90311', 'Life and disability cover'),
  ('80000000-0000-4000-8000-000000000004'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000005'::uuid, 'Investment', 'AG-DEMO-22007', 'Tax-free savings account'),
  ('80000000-0000-4000-8000-000000000005'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, 'b0000000-0000-4000-8000-000000000002'::uuid, 'Life cover', 'DSC-DEMO-55120', 'Life plan'),
  ('80000000-0000-4000-8000-000000000006'::uuid, 'c0000000-0000-4000-8000-000000000003'::uuid, 'b0000000-0000-4000-8000-000000000004'::uuid, 'Retirement annuity', 'MOM-DEMO-70014', 'Retirement annuity'),
  ('80000000-0000-4000-8000-000000000007'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, 'b0000000-0000-4000-8000-000000000001'::uuid, 'Vehicle insurance', 'SAN-DEMO-45990', 'Comprehensive motor cover'),
  ('80000000-0000-4000-8000-000000000008'::uuid, 'c0000000-0000-4000-8000-000000000005'::uuid, 'b0000000-0000-4000-8000-000000000003'::uuid, 'Life cover', 'SLM-DEMO-90877', 'Funeral and life cover')
on conflict do nothing;

insert into public.goals (id, client_id, household_id, name, category, current_amount, target_amount, target_date) values
  ('90000000-0000-4000-8000-000000000001'::uuid, null, 'd0000000-0000-4000-8000-000000000001'::uuid, 'Home Deposit', 'Property', 186000, 300000, (rsf_seed_ts(420, 9, 0) at time zone 'Africa/Johannesburg')::date),
  ('90000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'Emergency Fund', 'Safety net', 42000, 50000, (rsf_seed_ts(120, 9, 0) at time zone 'Africa/Johannesburg')::date),
  ('90000000-0000-4000-8000-000000000003'::uuid, 'c0000000-0000-4000-8000-000000000003'::uuid, null, 'Retirement top-up', 'Retirement', 1250000, 2000000, (rsf_seed_ts(2200, 9, 0) at time zone 'Africa/Johannesburg')::date),
  ('90000000-0000-4000-8000-000000000004'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, null, 'Children''s education', 'Education', 96000, 400000, (rsf_seed_ts(3000, 9, 0) at time zone 'Africa/Johannesburg')::date),
  ('90000000-0000-4000-8000-000000000005'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, null, 'Vehicle replacement', 'Vehicle', 38000, 120000, (rsf_seed_ts(600, 9, 0) at time zone 'Africa/Johannesburg')::date)
on conflict do nothing;

insert into public.workflows (id, client_id, provider_id, type, title, status, current_owner, current_step, next_action, due_date, priority, created_at, updated_at) values
  ('e0000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000001'::uuid, 'motor_claim', 'Motor claim', 'active', 'adviser', 4, 'Schedule vehicle assessment', rsf_seed_ts(0, 17, 0), 'high', rsf_seed_ts(-1, 10, 14), rsf_seed_ts(-1, 12, 3)),
  ('e0000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, 'b0000000-0000-4000-8000-000000000002'::uuid, 'policy_amendment', 'Policy amendment', 'active', 'provider', 3, 'Provider confirmation', rsf_seed_ts(2, 17, 0), 'normal', rsf_seed_ts(-8, 9, 0), rsf_seed_ts(-3, 9, 30)),
  ('e0000000-0000-4000-8000-000000000003'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'annual_review', 'Annual review', 'active', 'client', 2, 'Upload annual review documents', rsf_seed_ts(7, 17, 0), 'normal', rsf_seed_ts(-5, 9, 0), rsf_seed_ts(-4, 9, 5)),
  ('e0000000-0000-4000-8000-000000000004'::uuid, 'c0000000-0000-4000-8000-000000000003'::uuid, null, 'change_of_address', 'Change of address', 'active', 'client', 1, 'Upload proof of address (not older than 3 months)', rsf_seed_ts(-3, 17, 0), 'normal', rsf_seed_ts(-10, 14, 0), rsf_seed_ts(-10, 14, 5)),
  ('e0000000-0000-4000-8000-000000000005'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000003'::uuid, 'policy_amendment', 'Policy amendment', 'active', 'provider', 3, 'Provider confirmation', rsf_seed_ts(3, 17, 0), 'normal', rsf_seed_ts(-6, 11, 0), rsf_seed_ts(-2, 10, 0)),
  ('e0000000-0000-4000-8000-000000000006'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, null, 'bank_details_change', 'Change bank details', 'active', 'adviser', 1, 'Call client to verify the change (fraud check)', rsf_seed_ts(-2, 17, 0), 'high', rsf_seed_ts(-4, 16, 0), rsf_seed_ts(-4, 16, 10)),
  ('e0000000-0000-4000-8000-000000000007'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, 'b0000000-0000-4000-8000-000000000002'::uuid, 'document_request', 'IRP5 / tax certificate', 'active', 'adviser', 1, 'Request document from provider', rsf_seed_ts(1, 17, 0), 'normal', rsf_seed_ts(-1, 15, 0), rsf_seed_ts(-1, 15, 2))
on conflict do nothing;

insert into public.workflow_steps (id, workflow_id, position, step_key, label, owner, status, next_action, due_in_days, started_at, completed_at) values
  ('20000000-0000-4000-8000-000100000000'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 0, 'accident_captured', 'Accident captured', 'client', 'complete', 'Capture accident details and evidence', 0, rsf_seed_ts(-1, 10, 14), rsf_seed_ts(-1, 10, 42)),
  ('20000000-0000-4000-8000-000100000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 1, 'claim_submitted', 'Claim submitted', 'adviser', 'complete', 'Review evidence and submit claim to insurer', 1, rsf_seed_ts(-1, 10, 42), rsf_seed_ts(-1, 11, 6)),
  ('20000000-0000-4000-8000-000100000002'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 2, 'claim_number', 'Claim number received', 'provider', 'complete', 'Insurer to issue claim number', 2, rsf_seed_ts(-1, 11, 6), rsf_seed_ts(-1, 11, 49)),
  ('20000000-0000-4000-8000-000100000003'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 3, 'handler_assigned', 'Claims handler assigned', 'provider', 'complete', 'Insurer to assign a claims handler', 2, rsf_seed_ts(-1, 11, 49), rsf_seed_ts(-1, 12, 3)),
  ('20000000-0000-4000-8000-000100000004'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 4, 'vehicle_assessment', 'Vehicle assessment', 'adviser', 'current', 'Schedule vehicle assessment', 1, rsf_seed_ts(-1, 12, 3), null),
  ('20000000-0000-4000-8000-000100000005'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 5, 'assessment_submitted', 'Assessment submitted', 'provider', 'upcoming', 'Assessor to submit assessment report', 3, null, null),
  ('20000000-0000-4000-8000-000100000006'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 6, 'repair_quotation', 'Repair quotation', 'repairer', 'upcoming', 'Repairer to submit quotation', 3, null, null),
  ('20000000-0000-4000-8000-000100000007'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 7, 'insurer_approval', 'Insurer approval', 'provider', 'upcoming', 'Insurer to approve repair quotation', 3, null, null),
  ('20000000-0000-4000-8000-000100000008'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 8, 'repair_booking', 'Repair booking', 'adviser', 'upcoming', 'Book the vehicle in with the repairer', 2, null, null),
  ('20000000-0000-4000-8000-000100000009'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 9, 'vehicle_repair', 'Vehicle repair', 'repairer', 'upcoming', 'Repair the vehicle', 10, null, null),
  ('20000000-0000-4000-8000-000100000010'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 10, 'car_hire', 'Car hire', 'provider', 'upcoming', 'Arrange car hire while the vehicle is repaired', 1, null, null),
  ('20000000-0000-4000-8000-000100000011'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 11, 'vehicle_return', 'Vehicle return', 'repairer', 'upcoming', 'Return the repaired vehicle to the client', 2, null, null),
  ('20000000-0000-4000-8000-000100000012'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 12, 'claim_closed', 'Claim closed', 'adviser', 'upcoming', 'Confirm client is satisfied and close the claim', 2, null, null),
  ('20000000-0000-4000-8000-000200000000'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 0, 'request_received', 'Amendment requested', 'client', 'complete', 'Describe the change you need', 0, rsf_seed_ts(-8, 9, 0), rsf_seed_ts(-6, 10, 0)),
  ('20000000-0000-4000-8000-000200000001'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 1, 'amendment_prepared', 'Amendment prepared', 'adviser', 'complete', 'Prepare amendment instruction', 2, rsf_seed_ts(-6, 10, 0), rsf_seed_ts(-4, 11, 0)),
  ('20000000-0000-4000-8000-000200000002'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 2, 'sent_to_provider', 'Sent to provider', 'adviser', 'complete', 'Submit instruction to provider', 1, rsf_seed_ts(-4, 11, 0), rsf_seed_ts(-3, 9, 30)),
  ('20000000-0000-4000-8000-000200000003'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 3, 'provider_confirmation', 'Provider confirmation', 'provider', 'current', 'Provider confirmation', 5, rsf_seed_ts(-3, 9, 30), null),
  ('20000000-0000-4000-8000-000200000004'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 4, 'client_notified', 'Client notified', 'adviser', 'upcoming', 'Share updated schedule with client', 1, null, null),
  ('20000000-0000-4000-8000-000300000000'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 0, 'review_scheduled', 'Review scheduled', 'adviser', 'complete', 'Schedule annual review meeting', 3, rsf_seed_ts(-5, 9, 0), rsf_seed_ts(-4, 9, 0)),
  ('20000000-0000-4000-8000-000300000001'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 1, 'documents_requested', 'Documents requested', 'system', 'complete', 'Send document checklist to client', 0, rsf_seed_ts(-4, 9, 0), rsf_seed_ts(-4, 9, 5)),
  ('20000000-0000-4000-8000-000300000002'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 2, 'client_documents', 'Client documents', 'client', 'current', 'Upload annual review documents', 7, rsf_seed_ts(-4, 9, 5), null),
  ('20000000-0000-4000-8000-000300000003'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 3, 'adviser_preparation', 'Adviser preparation', 'adviser', 'upcoming', 'Prepare review pack', 5, null, null),
  ('20000000-0000-4000-8000-000300000004'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 4, 'review_meeting', 'Review meeting', 'adviser', 'upcoming', 'Hold review meeting', 7, null, null),
  ('20000000-0000-4000-8000-000300000005'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 5, 'record_signed', 'Record of advice signed', 'client', 'upcoming', 'Sign record of advice', 5, null, null),
  ('20000000-0000-4000-8000-000400000000'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 0, 'event_reported', 'Move reported', 'client', 'complete', 'Tell us your new address', 0, rsf_seed_ts(-10, 14, 0), rsf_seed_ts(-10, 14, 5)),
  ('20000000-0000-4000-8000-000400000001'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 1, 'proof_of_address', 'Proof of address', 'client', 'current', 'Upload proof of address (not older than 3 months)', 7, rsf_seed_ts(-10, 14, 5), null),
  ('20000000-0000-4000-8000-000400000002'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 2, 'adviser_review', 'Review information', 'adviser', 'upcoming', 'Review new address and proof of address', 2, null, null),
  ('20000000-0000-4000-8000-000400000003'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 3, 'notify_providers', 'Notify affected providers', 'adviser', 'upcoming', 'Send address update to each affected provider', 2, null, null),
  ('20000000-0000-4000-8000-000400000004'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 4, 'provider_confirmation', 'Provider confirmations', 'provider', 'upcoming', 'Providers to confirm the updated address', 5, null, null),
  ('20000000-0000-4000-8000-000400000005'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 5, 'confirm_completion', 'Confirm completion', 'adviser', 'upcoming', 'Confirm to the client that all records are updated', 1, null, null),
  ('20000000-0000-4000-8000-000500000000'::uuid, 'e0000000-0000-4000-8000-000000000005'::uuid, 0, 'request_received', 'Amendment requested', 'client', 'complete', 'Describe the change you need', 0, rsf_seed_ts(-6, 11, 0), rsf_seed_ts(-5, 9, 0)),
  ('20000000-0000-4000-8000-000500000001'::uuid, 'e0000000-0000-4000-8000-000000000005'::uuid, 1, 'amendment_prepared', 'Amendment prepared', 'adviser', 'complete', 'Prepare amendment instruction', 2, rsf_seed_ts(-5, 9, 0), rsf_seed_ts(-3, 15, 0)),
  ('20000000-0000-4000-8000-000500000002'::uuid, 'e0000000-0000-4000-8000-000000000005'::uuid, 2, 'sent_to_provider', 'Sent to provider', 'adviser', 'complete', 'Submit instruction to provider', 1, rsf_seed_ts(-3, 15, 0), rsf_seed_ts(-2, 10, 0)),
  ('20000000-0000-4000-8000-000500000003'::uuid, 'e0000000-0000-4000-8000-000000000005'::uuid, 3, 'provider_confirmation', 'Provider confirmation', 'provider', 'current', 'Provider confirmation', 5, rsf_seed_ts(-2, 10, 0), null),
  ('20000000-0000-4000-8000-000500000004'::uuid, 'e0000000-0000-4000-8000-000000000005'::uuid, 4, 'client_notified', 'Client notified', 'adviser', 'upcoming', 'Share updated schedule with client', 1, null, null),
  ('20000000-0000-4000-8000-000600000000'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 0, 'request_submitted', 'Request submitted', 'client', 'complete', 'Submit new bank details and bank confirmation letter', 0, rsf_seed_ts(-4, 16, 0), rsf_seed_ts(-4, 16, 10)),
  ('20000000-0000-4000-8000-000600000001'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 1, 'verify_identity', 'Verify identity', 'adviser', 'current', 'Call client to verify the change (fraud check)', 1, rsf_seed_ts(-4, 16, 10), null),
  ('20000000-0000-4000-8000-000600000002'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 2, 'submit_providers', 'Submit to providers', 'adviser', 'upcoming', 'Send debit-order change to providers', 1, null, null),
  ('20000000-0000-4000-8000-000600000003'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 3, 'provider_confirmation', 'Provider confirmation', 'provider', 'upcoming', 'Providers to confirm new debit order', 5, null, null),
  ('20000000-0000-4000-8000-000600000004'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 4, 'confirm_completion', 'Confirm completion', 'adviser', 'upcoming', 'Confirm completion to client', 1, null, null),
  ('20000000-0000-4000-8000-000700000000'::uuid, 'e0000000-0000-4000-8000-000000000007'::uuid, 0, 'request_submitted', 'Request submitted', 'client', 'complete', 'Tell us which document you need', 0, rsf_seed_ts(-1, 15, 0), rsf_seed_ts(-1, 15, 2)),
  ('20000000-0000-4000-8000-000700000001'::uuid, 'e0000000-0000-4000-8000-000000000007'::uuid, 1, 'request_to_provider', 'Requested from provider', 'adviser', 'current', 'Request document from provider', 1, rsf_seed_ts(-1, 15, 2), null),
  ('20000000-0000-4000-8000-000700000002'::uuid, 'e0000000-0000-4000-8000-000000000007'::uuid, 2, 'provider_issues', 'Provider issues document', 'provider', 'upcoming', 'Provider to issue document', 3, null, null),
  ('20000000-0000-4000-8000-000700000003'::uuid, 'e0000000-0000-4000-8000-000000000007'::uuid, 3, 'shared_with_client', 'Shared with you', 'adviser', 'upcoming', 'Upload document to client portal', 1, null, null)
on conflict do nothing;

insert into public.documents (id, client_id, workflow_id, doc_type, name, status, expiry_date, uploaded_at) values
  ('f0000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'id_document', 'ID document', 'current', null, rsf_seed_ts(-400, 9, 0)),
  ('f0000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'drivers_licence', 'Driver''s licence', 'current', (rsf_seed_ts(54, 9, 0) at time zone 'Africa/Johannesburg')::date, rsf_seed_ts(-1500, 9, 0)),
  ('f0000000-0000-4000-8000-000000000003'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'policy_schedule', 'Santam vehicle policy schedule', 'current', null, rsf_seed_ts(-90, 9, 0)),
  ('f0000000-0000-4000-8000-000000000004'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 'income_statement', 'Proof of income', 'missing', null, null),
  ('f0000000-0000-4000-8000-000000000005'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'investment_statement', 'Allan Gray TFSA statement', 'under_review', null, rsf_seed_ts(-2, 9, 0)),
  ('f0000000-0000-4000-8000-000000000006'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'valuation_certificate', 'Jewellery valuation certificate', 'current', (rsf_seed_ts(-20, 9, 0) at time zone 'Africa/Johannesburg')::date, rsf_seed_ts(-800, 9, 0)),
  ('f0000000-0000-4000-8000-000000000007'::uuid, 'c0000000-0000-4000-8000-000000000003'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 'proof_of_address', 'Proof of address', 'missing', null, null),
  ('f0000000-0000-4000-8000-000000000008'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, null, 'policy_schedule', 'Discovery life plan schedule', 'current', null, rsf_seed_ts(-200, 9, 0)),
  ('f0000000-0000-4000-8000-000000000009'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, null, 'drivers_licence', 'Driver''s licence', 'current', (rsf_seed_ts(700, 9, 0) at time zone 'Africa/Johannesburg')::date, rsf_seed_ts(-300, 9, 0))
on conflict do nothing;

insert into public.tasks (id, client_id, workflow_id, task_key, assignee_role, assigned_adviser_id, kind, title, description, due_date, status, priority, link) values
  ('60000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'licence_renewal', 'client', null, 'reminder', 'Driver''s licence expires in 54 days', 'Renew at your licensing centre, then upload the new card.', rsf_seed_ts(54, 9, 0), 'open', 'normal', '/client/documents'),
  ('60000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 'annual_review_docs', 'client', null, 'task', 'Annual review document outstanding', 'Upload your latest proof of income.', rsf_seed_ts(7, 9, 0), 'open', 'normal', '/client/documents'),
  ('60000000-0000-4000-8000-000000000003'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, null, 'confirm_policy_info', 'client', null, 'task', 'Policy information requires confirmation', 'Confirm the regular driver and overnight parking on your vehicle policy.', rsf_seed_ts(5, 9, 0), 'open', 'normal', '/client/profile'),
  ('60000000-0000-4000-8000-000000000004'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'schedule_assessment', 'adviser', 'a0000000-0000-4000-8000-000000000001'::uuid, 'task', 'Schedule vehicle assessment', 'Book Santam assessor for Lerato Molefe.', rsf_seed_ts(0, 17, 0), 'open', 'high', null),
  ('60000000-0000-4000-8000-000000000005'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 'follow_up_provider', 'adviser', 'a0000000-0000-4000-8000-000000000001'::uuid, 'task', 'Follow up with Discovery', 'Chase confirmation of policy amendment.', rsf_seed_ts(1, 9, 0), 'open', 'normal', null),
  ('60000000-0000-4000-8000-000000000006'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 'verify_bank_change', 'adviser', 'a0000000-0000-4000-8000-000000000001'::uuid, 'task', 'Verify bank details change by phone', 'Fraud check before submitting to providers.', rsf_seed_ts(-2, 9, 0), 'open', 'high', null),
  ('60000000-0000-4000-8000-000000000007'::uuid, 'c0000000-0000-4000-8000-000000000003'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 'proof_of_address', 'client', null, 'task', 'Upload proof of address', 'Needed to complete your change of address.', rsf_seed_ts(-3, 9, 0), 'open', 'normal', null),
  ('60000000-0000-4000-8000-000000000008'::uuid, 'c0000000-0000-4000-8000-000000000005'::uuid, null, 'annual_review_due', 'adviser', 'a0000000-0000-4000-8000-000000000002'::uuid, 'reminder', 'Annual review due next month', 'Schedule Bongani Dlamini annual review.', rsf_seed_ts(30, 9, 0), 'open', 'low', null)
on conflict do nothing;

insert into public.reminders (id, client_id, document_id, title, remind_at, channel) values
  ('40000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'f0000000-0000-4000-8000-000000000002'::uuid, 'Driver''s licence renewal', rsf_seed_ts(-6, 9, 0), 'email')
on conflict do nothing;

insert into public.claims (id, client_id, workflow_id, provider_id, claim_number, claim_type, status, incident_at, incident_location, latitude, longitude, description, vehicle_description, other_party, witnesses, captured_offline, created_at) values
  ('70000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'b0000000-0000-4000-8000-000000000001'::uuid, 'SAN-CLM-DEMO-78213', 'motor', 'in_progress', rsf_seed_ts(-1, 9, 52), 'Main Road & Belmont Road, Rondebosch', -33.9611, 18.4721, 'Rear-ended at a red traffic light. No injuries. Rear bumper and boot damaged.', '2021 Toyota Corolla Cross · CA 123-456', '{"name":"Pieter Smit","registration":"CA 987-654","insurer":"Unknown","phone":"071 555 0190"}'::jsonb, '[{"name":"Nomsa Khumalo","phone":"079 555 0150"}]'::jsonb, false, rsf_seed_ts(-1, 10, 14))
on conflict do nothing;

insert into public.claim_evidence (id, claim_id, evidence_type, notes, captured, captured_at) values
  ('10000000-0000-4000-8000-000000000001'::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'location', 'Accident location', true, rsf_seed_ts(-1, 10, 14)),
  ('10000000-0000-4000-8000-000000000002'::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'scene_photos', 'Scene photographs', true, rsf_seed_ts(-1, 10, 14)),
  ('10000000-0000-4000-8000-000000000003'::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'other_vehicle', 'Other vehicle', true, rsf_seed_ts(-1, 10, 14)),
  ('10000000-0000-4000-8000-000000000004'::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'other_insurer', 'Other insurer', false, rsf_seed_ts(-1, 10, 14)),
  ('10000000-0000-4000-8000-000000000005'::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'witness', 'Witness', true, rsf_seed_ts(-1, 10, 14)),
  ('10000000-0000-4000-8000-000000000006'::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'voice_note', 'Voice description', false, rsf_seed_ts(-1, 10, 14))
on conflict do nothing;

insert into public.service_requests (id, client_id, workflow_id, request_type, details, status, created_at) values
  ('50000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 'bank_details_change', '{"note":"New account at Capitec"}'::jsonb, 'in_progress', rsf_seed_ts(-4, 16, 0)),
  ('50000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, 'e0000000-0000-4000-8000-000000000007'::uuid, 'irp5_request', '{"providerId":"b0000000-0000-4000-8000-000000000002","taxYear":"2026"}'::jsonb, 'in_progress', rsf_seed_ts(-1, 15, 0))
on conflict do nothing;

insert into public.activity_events (id, client_id, workflow_id, actor_type, actor_name, event_type, message, occurred_at) values
  ('30000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'client', 'Lerato Molefe', 'workflow', 'Client submitted accident evidence', rsf_seed_ts(-1, 10, 14)),
  ('30000000-0000-4000-8000-000000000002'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'adviser', 'Sipho Ndlovu', 'workflow', 'Adviser reviewed submission', rsf_seed_ts(-1, 10, 42)),
  ('30000000-0000-4000-8000-000000000003'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'adviser', 'Sipho Ndlovu', 'workflow', 'Claim submitted to Santam', rsf_seed_ts(-1, 11, 6)),
  ('30000000-0000-4000-8000-000000000004'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'provider', 'Santam', 'workflow', 'Santam claim number received', rsf_seed_ts(-1, 11, 49)),
  ('30000000-0000-4000-8000-000000000005'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000001'::uuid, 'system', 'System', 'workflow', 'Vehicle assessment requested', rsf_seed_ts(-1, 12, 3)),
  ('30000000-0000-4000-8000-000000000006'::uuid, 'c0000000-0000-4000-8000-000000000002'::uuid, 'e0000000-0000-4000-8000-000000000002'::uuid, 'adviser', 'Sipho Ndlovu', 'workflow', 'Amendment instruction sent to Discovery', rsf_seed_ts(-3, 9, 30)),
  ('30000000-0000-4000-8000-000000000007'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000003'::uuid, 'system', 'System', 'workflow', 'Annual review document checklist sent', rsf_seed_ts(-4, 9, 5)),
  ('30000000-0000-4000-8000-000000000008'::uuid, 'c0000000-0000-4000-8000-000000000003'::uuid, 'e0000000-0000-4000-8000-000000000004'::uuid, 'client', 'Johan Pretorius', 'workflow', 'Client reported a move', rsf_seed_ts(-10, 14, 5)),
  ('30000000-0000-4000-8000-000000000009'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'e0000000-0000-4000-8000-000000000005'::uuid, 'adviser', 'Sipho Ndlovu', 'workflow', 'Beneficiary change sent to Sanlam', rsf_seed_ts(-2, 10, 0)),
  ('30000000-0000-4000-8000-000000000010'::uuid, 'c0000000-0000-4000-8000-000000000004'::uuid, 'e0000000-0000-4000-8000-000000000006'::uuid, 'client', 'Ayesha Patel', 'workflow', 'Client requested bank details change', rsf_seed_ts(-4, 16, 10))
on conflict do nothing;

insert into public.chat_conversations (id, client_id, title) values
  ('0c000000-0000-4000-8000-000000000001'::uuid, 'c0000000-0000-4000-8000-000000000001'::uuid, 'Claim status question')
on conflict do nothing;

insert into public.chat_messages (id, conversation_id, role, content) values
  ('0d000000-0000-4000-8000-000000000001'::uuid, '0c000000-0000-4000-8000-000000000001'::uuid, 'user', 'What does "waiting on provider" mean for my motor claim?'),
  ('0d000000-0000-4000-8000-000000000002'::uuid, '0c000000-0000-4000-8000-000000000001'::uuid, 'assistant', 'It means the next step is with Santam, not with you or Royal Square. Right now your claim is at vehicle assessment. You can follow each step under Claims.')
on conflict do nothing;

-- Link any auth users that already exist with the demo emails.
update public.clients c set profile_id = u.id from auth.users u
  where lower(u.email) = lower(c.email) and c.profile_id is null;
update public.advisers a set profile_id = u.id from auth.users u
  where lower(u.email) = lower(a.email) and a.profile_id is null;
update public.profiles p set role = 'adviser' from public.advisers a
  where a.profile_id = p.id and p.role = 'client';
update public.chat_conversations cc set profile_id = c.profile_id from public.clients c
  where cc.client_id = c.id and cc.profile_id is null and c.profile_id is not null;

-- The helper is only needed while seeding.
drop function if exists public.rsf_seed_ts(int, int, int);
