/**
 * Generates supabase/seed.sql from src/data/mockData.js so the database demo
 * and the no-Supabase demo always show the same story.
 *
 *   npm run seed:generate
 *
 * Timestamps are written relative to the day the seed is RUN (not generated),
 * in South African time, so "Due today" and "expires in 54 days" stay true.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

process.env.TZ = 'Africa/Johannesburg';
const { createInitialState } = await import('../src/data/mockData.js');

const GENERATED_AT = new Date();
const state = createInitialState();

// ── Stable, readable UUIDs: prefix identifies the table, suffix the mock id ──
const PREFIX = {
  adviser: 'a0000000', provider: 'b0000000', client: 'c0000000', household: 'd0000000',
  workflow: 'e0000000', document: 'f0000000', goal: '90000000', product: '80000000',
  claim: '70000000', task: '60000000', request: '50000000', reminder: '40000000',
  event: '30000000', step: '20000000', evidence: '10000000', chat: '0c000000', message: '0d000000',
};
const num = (mockId) => Number(String(mockId).replace(/\D/g, ''));
const id = (kind, mockId) => (mockId == null ? null : `${PREFIX[kind]}-0000-4000-8000-${String(num(mockId)).padStart(12, '0')}`);
const stepId = (wfMockId, pos) => `${PREFIX.step}-0000-4000-8000-${String(num(wfMockId)).padStart(4, '0')}${String(pos).padStart(8, '0')}`;

// ── SQL literals ──
const q = (v) => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v == null ? 'null' : String(Number(v)));
const b = (v) => (v ? 'true' : 'false');
const j = (v) => (v == null ? 'null' : `${q(JSON.stringify(v))}::jsonb`);
const uuid = (v) => (v == null ? 'null' : `'${v}'::uuid`);

const DAY = 86400000;
function localMidnight(d) {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  return x;
}
/** timestamptz relative to seed-run day, preserving SA clock time. */
function ts(value) {
  if (!value) return 'null';
  const d = new Date(value);
  const days = Math.round((localMidnight(d) - localMidnight(GENERATED_AT)) / DAY);
  return `rsf_seed_ts(${days}, ${d.getHours()}, ${d.getMinutes()})`;
}
function date(value) {
  return value ? `(${ts(value)} at time zone 'Africa/Johannesburg')::date` : 'null';
}

function insert(table, columns, rows) {
  if (!rows.length) return '';
  const values = rows.map((r) => `  (${r.join(', ')})`).join(',\n');
  return `insert into public.${table} (${columns.join(', ')}) values\n${values}\non conflict do nothing;\n\n`;
}

const s = state;
let sql = `-- =====================================================================
-- Royal Square Financial — demo seed data (FICTIONAL people and policies)
-- GENERATED by scripts/generate-seed.mjs from src/data/mockData.js.
-- Do not hand-edit: change mockData.js and run \`npm run seed:generate\`.
--
-- Run AFTER supabase/schema.sql. Safe to re-run (on conflict do nothing).
-- Provider integrations are mock only.
--
-- To sign in as the demo users, create auth users (Authentication → Users →
-- Add user) with these emails; the auth trigger links them automatically:
--   Client : lerato.molefe@example.demo
--   Adviser: sipho.ndlovu@royalsquare.demo
-- =====================================================================

-- Timestamp helper: day offset + South African clock time, relative to today.
create or replace function public.rsf_seed_ts(day_offset int, hh int, mi int)
returns timestamptz
language sql stable
as $$
  select (date_trunc('day', now() at time zone 'Africa/Johannesburg')
          + make_interval(days => day_offset, hours => hh, mins => mi)) at time zone 'Africa/Johannesburg';
$$;

`;

sql += insert('advisers', ['id', 'full_name', 'email', 'phone', 'region', 'fsp_rep_number'],
  s.advisers.map((a) => [uuid(id('adviser', a.id)), q(a.name), q(a.email), q(a.phone), q(a.region), q(a.fspRepNumber)]));

sql += insert('providers', ['id', 'name', 'category', 'contact_email', 'avg_response_days', 'integration_mode'],
  s.providers.map((p) => [uuid(id('provider', p.id)), q(p.name), q(p.category), q(p.contact), n(p.avgResponseDays), q(p.integration)]));

sql += insert('clients', ['id', 'first_name', 'last_name', 'email', 'phone', 'id_number_masked', 'date_of_birth', 'address_line', 'city', 'postal_code', 'occupation', 'vehicle_description', 'total_assets', 'total_liabilities'],
  s.clients.map((c) => [uuid(id('client', c.id)), q(c.firstName), q(c.lastName), q(c.email), q(c.phone), q(c.idNumberMasked), `${q(c.dateOfBirth)}::date`, q(c.address), q(c.city), q(c.postalCode), q(c.occupation), q(c.vehicle), n(c.totalAssets), n(c.totalLiabilities)]));

sql += insert('client_adviser_assignments', ['client_id', 'adviser_id', 'is_primary'],
  s.clients.flatMap((c) => c.adviserIds.map((a, i) => [uuid(id('client', c.id)), uuid(id('adviser', a)), b(i === 0)])));

sql += insert('households', ['id', 'name'], s.households.map((h) => [uuid(id('household', h.id)), q(h.name)]));
sql += insert('household_members', ['household_id', 'client_id'],
  s.households.flatMap((h) => h.memberIds.map((m) => [uuid(id('household', h.id)), uuid(id('client', m))])));

sql += insert('client_products', ['id', 'client_id', 'provider_id', 'product_type', 'policy_number', 'description'],
  s.clientProducts.map((p) => [uuid(id('product', p.id)), uuid(id('client', p.clientId)), uuid(id('provider', p.providerId)), q(p.type), q(p.policyNumber), q(p.description)]));

sql += insert('goals', ['id', 'client_id', 'household_id', 'name', 'category', 'current_amount', 'target_amount', 'target_date'],
  s.goals.map((g) => [uuid(id('goal', g.id)), uuid(id('client', g.clientId)), uuid(id('household', g.householdId)), q(g.name), q(g.category), n(g.currentAmount), n(g.targetAmount), date(g.targetDate)]));

sql += insert('workflows', ['id', 'client_id', 'provider_id', 'type', 'title', 'status', 'current_owner', 'current_step', 'next_action', 'due_date', 'priority', 'created_at', 'updated_at'],
  s.workflows.map((w) => [uuid(id('workflow', w.id)), uuid(id('client', w.clientId)), uuid(id('provider', w.providerId)), q(w.type), q(w.title), q(w.status), q(w.currentOwner), n(w.currentStep), q(w.nextAction), ts(w.dueDate), q(w.priority), ts(w.createdAt), ts(w.updatedAt)]));

sql += insert('workflow_steps', ['id', 'workflow_id', 'position', 'step_key', 'label', 'owner', 'status', 'next_action', 'due_in_days', 'started_at', 'completed_at'],
  s.workflows.flatMap((w) => w.steps.map((st, i) => [uuid(stepId(w.id, i)), uuid(id('workflow', w.id)), n(i), q(st.key), q(st.label), q(st.owner), q(st.status), q(st.nextAction), n(st.dueInDays), ts(st.startedAt), ts(st.completedAt)])));

sql += insert('documents', ['id', 'client_id', 'workflow_id', 'doc_type', 'name', 'status', 'expiry_date', 'uploaded_at'],
  s.documents.map((d) => [uuid(id('document', d.id)), uuid(id('client', d.clientId)), uuid(id('workflow', d.workflowId)), q(d.type), q(d.name), q(d.status), date(d.expiryDate), ts(d.uploadedAt)]));

sql += insert('tasks', ['id', 'client_id', 'workflow_id', 'task_key', 'assignee_role', 'assigned_adviser_id', 'kind', 'title', 'description', 'due_date', 'status', 'priority', 'link'],
  s.tasks.map((t) => [uuid(id('task', t.id)), uuid(id('client', t.clientId)), uuid(id('workflow', t.workflowId)), q(t.taskKey), q(t.assignee), uuid(id('adviser', t.adviserId)), q(t.kind), q(t.title), q(t.description), ts(t.dueDate), q(t.status), q(t.priority), q(t.link)]));

sql += insert('reminders', ['id', 'client_id', 'document_id', 'title', 'remind_at', 'channel'],
  s.reminders.map((r) => [uuid(id('reminder', r.id)), uuid(id('client', r.clientId)), uuid(id('document', r.documentId)), q(r.title), ts(r.remindAt), q(r.channel)]));

sql += insert('claims', ['id', 'client_id', 'workflow_id', 'provider_id', 'claim_number', 'claim_type', 'status', 'incident_at', 'incident_location', 'latitude', 'longitude', 'description', 'vehicle_description', 'other_party', 'witnesses', 'captured_offline', 'created_at'],
  s.claims.map((c) => [uuid(id('claim', c.id)), uuid(id('client', c.clientId)), uuid(id('workflow', c.workflowId)), uuid(id('provider', c.providerId)), q(c.claimNumber), q(c.type), q('in_progress'), ts(c.incidentAt), q(c.location), n(c.coordinates?.lat), n(c.coordinates?.lng), q(c.description), q(c.vehicle), j(c.otherParty), j(c.witnesses), b(c.capturedOffline), ts(c.createdAt)]));

sql += insert('claim_evidence', ['id', 'claim_id', 'evidence_type', 'notes', 'captured', 'captured_at'],
  s.claims.flatMap((c) => c.evidence.map((e) => [uuid(id('evidence', e.id)), uuid(id('claim', c.id)), q(e.type), q(e.label), b(e.captured), ts(c.createdAt)])));

sql += insert('service_requests', ['id', 'client_id', 'workflow_id', 'request_type', 'details', 'status', 'created_at'],
  s.serviceRequests.map((r) => {
    const details = { ...r.details };
    if (details.providerId) details.providerId = id('provider', details.providerId);
    return [uuid(id('request', r.id)), uuid(id('client', r.clientId)), uuid(id('workflow', r.workflowId)), q(r.type), j(details), q(r.status), ts(r.createdAt)];
  }));

sql += insert('activity_events', ['id', 'client_id', 'workflow_id', 'actor_type', 'actor_name', 'event_type', 'message', 'occurred_at'],
  s.activityEvents.map((e) => [uuid(id('event', e.id)), uuid(id('client', e.clientId)), uuid(id('workflow', e.workflowId)), q(e.actorType), q(e.actorName), q('workflow'), q(e.message), ts(e.at)]));

// A short example conversation (profile_id is linked once Lerato signs up).
sql += insert('chat_conversations', ['id', 'client_id', 'title'], [[uuid(id('chat', 1)), uuid(id('client', 'c1')), q('Claim status question')]]);
sql += insert('chat_messages', ['id', 'conversation_id', 'role', 'content'], [
  [uuid(id('message', 1)), uuid(id('chat', 1)), q('user'), q('What does "waiting on provider" mean for my motor claim?')],
  [uuid(id('message', 2)), uuid(id('chat', 1)), q('assistant'), q('It means the next step is with Santam, not with you or Royal Square. Right now your claim is at vehicle assessment. You can follow each step under Claims.')],
]);

sql += `-- Link any auth users that already exist with the demo emails.
update public.clients c set profile_id = u.id from auth.users u
  where lower(u.email) = lower(c.email) and c.profile_id is null;
update public.advisers a set profile_id = u.id from auth.users u
  where lower(u.email) = lower(a.email) and a.profile_id is null;
update public.profiles p set role = 'adviser' from public.advisers a
  where a.profile_id = p.id and p.role = 'client';
update public.chat_conversations cc set profile_id = c.profile_id from public.clients c
  where cc.client_id = c.id and cc.profile_id is null and c.profile_id is not null;

-- The helper is only needed while seeding.
drop function if exists public.rsf_seed_ts(int, int, int);
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../supabase/seed.sql');
writeFileSync(out, sql);
console.log(`Wrote ${out}`);
